name: 01 - Building Blocks
on:
    pull_request:
    workflow_dispatch:

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello, world"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Successful Step
              run: |
                  echo "I will succeed"
                  exit 0
            - name: Say goodbye
              run: echo "Say goodbye"
